spring.application.name=westendsgeschichte

# PostgreSQL (Render)
spring.datasource.url=jdbc:postgresql://dpg-d7j5d8ho3t8c73b4oe00-a/westendsgeschichtedb
spring.datasource.username=westendsgeschichtedb_user
spring.datasource.password=fUzmSYijGfIUXYEuxdVyuk9PgAkVc5NF

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}
